import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Storage } from "@aws-amplify/storage"
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { Amplify } from 'aws-amplify';
import awsExports from '../src/aws-exports';
import {useState, useEffect} from 'react'




export default function Home() {

Amplify.configure(awsExports);

const [data, setData] = useState<any>([])
const [selectedVideo, setSelectedVideo] = useState<any>('')


  useEffect(() => {

    Storage.list('') // for listing ALL files without prefix, pass '' instead
      .then(({ results }) => {
        console.log(results)
        setData(results)
        setSelectedVideo(results[1].key)
      })
      .catch((err) => console.log(err));
   
  }, [])
  
  


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.content_container}>

          <div className={styles.video_player_container}>

            {data.length > 0 ?
              <div>
                <video height={500} width={900} controls key={selectedVideo} className={styles.video}>
                  <source src={`https://d2by0efpla5ofl.cloudfront.net/public/${selectedVideo}`}/>
                </video>
              </div> 
            : 
              <div>loading videos...</div>
            }

          </div>

          <div className={styles.video_list_container}>
            {data.map((el: any, index: number) => el.key != '' ? <span key={index} className={styles.video_list_element} onClick={() => setSelectedVideo(el.key)}>{el.key.replace('.mp4', '')}</span> : null)}

          </div>

        </div>

      {/* <Authenticator>
      {({ signOut, user }) => (
        <main>
          <h1>Hello {user?.username}</h1>
          <button onClick={signOut}>Sign out</button>
        </main>
      )}
      </Authenticator> */}

        {/* {data.length > 0 ?
          <div>
            <video height={400} width={700} controls>
              <source src={`https://d2by0efpla5ofl.cloudfront.net/public/${data[1]?.key}`}/>
            </video>
          </div> 
        : 
          <div>loading videos...</div>
        } */}


        
      </main>
    </>
  )
}
