import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Storage } from "@aws-amplify/storage"
import '@aws-amplify/ui-react/styles.css';
import { Amplify } from 'aws-amplify';
import awsExports from '../aws_exports/aws-exports';
import {useState, useEffect} from 'react'
import { Auth } from 'aws-amplify';

export default function Videos() {

    Amplify.configure({...awsExports, ssr: true});

    const [data, setData] = useState<any>([])
    const [selectedVideo, setSelectedVideo] = useState<any>('')
    const [userName, setUserName] = useState<string>('')

    async function isUserAuth() {
        try {
            await Auth.currentAuthenticatedUser();
            return true;
        } catch {
            return false;
        }
      }
    
    isUserAuth()
        .then((res) => {
          if (res == false){
            window.location.replace("https://main.d176952duc25ab.amplifyapp.com/")
          }
        })
        .catch((err) => console.log(err))

    useEffect(() => {

        Storage.list('', {level: 'public'}) // for listing ALL files without prefix, pass '' instead
          .then(({ results }) => {
            // console.log(results)
            setData(results)
            setSelectedVideo(results[1].key)
          })
          .catch((err) => console.log(err));

          Auth.currentAuthenticatedUser()
          .then((res) => setUserName(res.username))
          .catch((err) => console.log(err))
       
      }, [])

    return (
        <>
            <Head>
            <title>Streaming Service</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>

                <div className={styles.user_login}>
                    <span>{userName}</span>
                    <button onClick={() => {
                        Auth.signOut()
                        .then((res) => window.location.replace("https://main.d176952duc25ab.amplifyapp.com/"))
                    }}>
                        Sign Out
                    </button>
                </div>

                <div className={styles.content_container}>

                    <div className={styles.video_player_container}>

                        {data.length > 0 ?
                        <div>
                            <video height={500} width={900} controls key={selectedVideo} className={styles.video}>
                            <source src={`https://d2by0efpla5ofl.cloudfront.net/public/${selectedVideo}`}/>
                            </video>
                        </div> 
                        : 
                        <div>loading videos...</div>
                        }

                    </div>

                    <div className={styles.video_list_container}>

                        {data.map((el: any, index: number) => el.key != '' ? <span key={index} className={styles.video_list_element} onClick={() => setSelectedVideo(el.key)}>{el.key.replace('.mp4', '')}</span> : null)}

                    </div>

                </div>

            </main>

        </>
    )
}